# Cinder
- name: Install Cinder packages
  apt:
    name:
      - cinder-api
      - cinder-scheduler
      - python3-cinderclient
    state: present

- name: Configure Cinder
  lineinfile:
    path: /etc/cinder/cinder.conf
    regexp: "^#?connection=.*"
    line: "connection = mysql+pymysql://cinder:{{ db_password }}@{{ controller_ip }}/cinder"

#- name: Populate Cinder database
#  shell: |
#    su -s /bin/bash cinder -c "cinder-manage db sync"

- name: Restart Cinder services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
#    - cinder-api
    - cinder-scheduler
