# Neutron
- name: Install Neutron packages
  apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
    state: present

- name: Configure Neutron
  lineinfile:
    path: /etc/neutron/neutron.conf
    regexp: "^#?connection=.*"
    line: "connection = mysql+pymysql://neutron:{{ db_password }}@{{ controller_ip }}/neutron"

#- name: Populate Neutron database
#  shell: |
#    su -s /bin/bash neutron -c "neutron-db-manage upgrade head"

- name: Restart Neutron services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
